import { HttpClient } from '@angular/common/http';
import { Injectable } from '@angular/core';
import {
  FormBuilder,
  FormControl,
  FormGroup,
  Validators,
} from '@angular/forms';
import { BehaviorSubject, Observable, Subject, map } from 'rxjs';
import { MatSnackBar } from '@angular/material/snack-bar';

@Injectable({
  providedIn: 'root',
})
export class ControlService {
  constructor(private fb: FormBuilder, private _snackBar: MatSnackBar) {}

  openSnackBar(message: string, duration: number) {
    this._snackBar.open(message, 'Bezárás', {
      duration: duration * 1000,
    });
  }

  actualPersonalPage = new BehaviorSubject<number>(0);

  user = {
    _id: new FormControl(null, [Validators.required]),
    email: new FormControl(null, [Validators.required, Validators.email]),
    username: new FormControl(null, [
      Validators.required,
      Validators.minLength(3),
      Validators.maxLength(10),
    ]),
    oldPassword: new FormControl(null, Validators.required),
    password: new FormControl(null, [
      Validators.required,
      Validators.pattern(
        '^(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9])(?=.*?[^A-Za-z0-9]).{8,}$'
      ),
    ]),
    confirmPassword: new FormControl(null, [
      Validators.required,
      Validators.pattern(
        '^(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9])(?=.*?[^A-Za-z0-9]).{8,}$'
      ),
    ]),
    firstName: new FormControl(null, [
      Validators.required,
      Validators.pattern('^[A-Ű][a-ű]{1,29}$'),
    ]),
    lastName: new FormControl(null, [
      Validators.required,
      Validators.pattern('^[A-Ű][a-ű]{1,29}$'),
    ]),
    birthDate: new FormControl(null, [Validators.required]),
    phone: new FormControl(null, [
      Validators.required,
      Validators.pattern(
        '^[+]?[(]?[0-9]{3}[)]?[-s.]?[0-9]{3}[-s.]?[0-9]{4,6}$'
      ),
    ]),
    personalId: new FormControl(null, [
      Validators.required,
      Validators.minLength(5),
      Validators.maxLength(10),
    ]),
    drivingLicense: new FormControl(null, [
      Validators.required,
      Validators.minLength(5),
      Validators.maxLength(10),
    ]),
    address: new FormGroup({
      city: new FormControl(null, [
        Validators.required,
        Validators.minLength(5),
        Validators.maxLength(20),
      ]),
      street: new FormControl(null, [
        Validators.required,
        Validators.minLength(5),
        Validators.maxLength(40),
      ]),
      houseNumber: new FormControl(null, [
        Validators.required,
        Validators.pattern('^[0-9]*$'),
      ]),
      floor: new FormControl(null, [Validators.pattern('^[0-9]*$')]),
      flatNumber: new FormControl(null, [Validators.pattern('^[0-9]*$')]),
      zip: new FormControl(null, [
        Validators.required,
        Validators.pattern('^[0-9]*$'),
      ]),
    }),
  };

  order = {
    _id: new FormControl(null, [Validators.required]),
    userId: new FormControl(null, [Validators.required]),
    carId: new FormControl(null, [Validators.required]),
    date: new FormControl(null, [Validators.required]),
    startDate: new FormControl(null, [Validators.required]),
    endDate: new FormControl(null, [Validators.required]),
    duration: new FormControl(null, [Validators.required]),
    price: new FormControl(null, [Validators.required]),
  };

  car = {
    _id: [{ value: null, disabled: true }],
    make: [null, Validators.required],
    model: [null, Validators.required],
    price: [null, Validators.required],
    fuel: [null, Validators.required],
    year: [null, [Validators.required, Validators.min(1960)]],
    transmission: [null, Validators.required],
    features: this.fb.group({
      color: [null, Validators.required],
      bodyStyle: [null, Validators.required],
      numberOfDoors: [null, Validators.required],
      numberOfSeats: [null, Validators.required],
      powerHp: [null, Validators.required],
      cubicCapacity: [null, Validators.required],
      fuelConsumption: [null, Validators.required],
      airCondition: [null, Validators.required],
    }),
    discount: [null, Validators.required],
    available: [null, Validators.required],
  };

  carOptions = {
    make: [
      { key: 'Audi', value: 'audi' },
      { key: 'BMW', value: 'bmw' },
      { key: 'Citroen', value: 'citroen' },
      { key: 'Dacia', value: 'dacia' },
      { key: 'Fiat', value: 'fiat' },
      { key: 'Ford', value: 'ford' },
      { key: 'Hyundai', value: 'hyundai' },
      { key: 'Honda', value: 'honda' },
      { key: 'Jaguar', value: 'jaguar' },
      { key: 'Mazda', value: 'mazda' },
      { key: 'Mercedes', value: 'mercedes' },
      { key: 'Nissan', value: 'nissan' },
      { key: 'Opel', value: 'opel' },
      { key: 'Renault', value: 'renault' },
      { key: 'Seat', value: 'seat' },
      { key: 'Skoda', value: 'skoda' },
      { key: 'Toyota', value: 'toyota' },
      { key: 'Volkswagen', value: 'volkswagen' },
    ],
    model: {
      audi: [
        { key: 'A1', value: 'a1' },
        { key: 'A2', value: 'a2' },
        { key: 'A3', value: 'a3' },
        { key: 'A4', value: 'a4' },
        { key: 'A5', value: 'a5' },
        { key: 'A6', value: 'a6' },
        { key: 'A7', value: 'a6' },
        { key: 'A8', value: 'a6' },
        { key: 'Q2', value: 'q2' },
        { key: 'Q3', value: 'q3' },
        { key: 'Q4', value: 'q4' },
        { key: 'Q5', value: 'q5' },
        { key: 'Q6', value: 'q6' },
        { key: 'Q7', value: 'q7' },
        { key: 'Q8', value: 'q8' },
        { key: 'S1', value: 's1' },
        { key: 'S2', value: 's2' },
        { key: 'S3', value: 's3' },
        { key: 'S4', value: 's4' },
        { key: 'S5', value: 's5' },
        { key: 'S6', value: 's6' },
        { key: 'S7', value: 's6' },
        { key: 'S8', value: 's6' },
        { key: 'TT', value: 'tt' },
      ],
      bmw: [
        { key: 'X1', value: 'x1' },
        { key: 'X2', value: 'x2' },
        { key: 'X3', value: 'x3' },
        { key: 'X4', value: 'x4' },
        { key: 'X5', value: 'x5' },
        { key: 'X6', value: 'x6' },
        { key: '1', value: '1' },
        { key: '2', value: '2' },
        { key: '3', value: '3' },
        { key: '4', value: '4' },
        { key: '5', value: '5' },
        { key: '6', value: '6' },
        { key: '7', value: '7' },
        { key: '8', value: '8' },
        { key: 'Z3', value: 'z3' },
        { key: 'Z4', value: 'z4' },
      ],
      citroen: [
        { key: 'Berlingo', value: 'berlingo' },
        { key: 'C-Elysee', value: 'c-elysee' },
        { key: 'C1', value: 'c1' },
        { key: 'C2', value: 'c2' },
        { key: 'C3', value: 'c3' },
        { key: 'C4', value: 'c4' },
        { key: 'C5', value: 'c5' },
        { key: 'C6', value: 'c6' },
        { key: 'C7', value: 'c6' },
        { key: 'C8', value: 'c6' },
        { key: 'DS', value: 'ds' },
        { key: 'DS3', value: 'ds3' },
        { key: 'DS4', value: 'ds4' },
        { key: 'DS5', value: 'ds5' },
        { key: 'Jumper', value: 'jumper' },
        { key: 'Saxo', value: 'saxo' },
        { key: 'Xsara', value: 'xsara' },
      ],
      dacia: [
        { key: 'Dokker', value: 'dokker' },
        { key: 'Duster', value: 'duster' },
        { key: 'Lodgy', value: 'lodgy' },
        { key: 'Logan', value: 'logan' },
        { key: 'Sandero', value: 'sandero' },
        { key: 'Spring', value: 'spring' },
      ],
      fiat: [
        { key: '500', value: '500' },
        { key: '500L', value: '500L' },
        { key: 'Bravo', value: 'Bravo' },
        { key: 'Doblo', value: 'doblo' },
        { key: 'Ducato', value: 'ducato' },
        { key: 'Multipla', value: 'multipla' },
        { key: 'Panda', value: 'panda' },
        { key: 'Punto', value: 'punto' },
        { key: 'Stilo', value: 'stilo' },
        { key: 'Tipo', value: 'tipo' },
      ],
      ford: [
        { key: 'C-Max', value: 'c-max' },
        { key: 'Ecosport', value: 'ecosport' },
        { key: 'Fiesta', value: 'fiesta' },
        { key: 'Focus', value: 'focus' },
        { key: 'Fusion', value: 'fusion' },
        { key: 'Mondeo', value: 'mondeo' },
        { key: 'Mustang', value: 'mustang' },
        { key: 'Puma', value: 'puma' },
        { key: 'Ranger', value: 'ranger' },
        { key: 'S-Max', value: 's-max' },
      ],
      honda: [
        { key: 'Accord', value: 'accord' },
        { key: 'Civic', value: 'civic' },
        { key: 'CR-V', value: 'cr-v' },
        { key: 'FR-V', value: 'fr-v' },
        { key: 'HR-V', value: 'hr-v' },
        { key: 'Jazz', value: 'jazz' },
      ],
      hyundai: [
        { key: 'Elantra', value: 'accord' },
        { key: 'Getz', value: 'civic' },
        { key: 'i10', value: 'i10' },
        { key: 'i20', value: 'i20' },
        { key: 'i30', value: 'i30' },
        { key: 'i40', value: 'i40' },
        { key: 'Ioniq', value: 'ioniq' },
        { key: 'ix20', value: 'ix20' },
        { key: 'ix35', value: 'ix35' },
        { key: 'ix55', value: 'ix55' },
        { key: 'Kona', value: 'kona' },
        { key: 'Santa Fe', value: 'santafe' },
        { key: 'Tucson', value: 'tucson' },
      ],
      jaguar: [
        { key: 'E-Pace', value: 'e-pace' },
        { key: 'F-Pace', value: 'f-pace' },
        { key: 'F-Type', value: 'f-type' },
        { key: 'I-Pace', value: 'i-pace' },
        { key: 'S-Type', value: 's-type' },
        { key: 'X-Type', value: 'x-type' },
        { key: 'XE', value: 'xe' },
        { key: 'XF', value: 'xf' },
        { key: 'XJ', value: 'xj' },
      ],
      kia: [
        { key: "Cee'd", value: 'ceed' },
        { key: "Pro Cee'd", value: 'proceed' },
        { key: 'Niro', value: 'niro' },
        { key: 'Optima', value: 'optima' },
        { key: 'Picanto', value: 'picantoe' },
        { key: 'Sorento', value: 'sorento' },
        { key: 'Soul', value: 'soul' },
        { key: 'Stinger', value: 'stinger' },
        { key: 'XCeed', value: 'xceed' },
      ],
      lexus: [
        { key: 'GS', value: 'gs' },
        { key: 'IS', value: 'is' },
        { key: 'LS', value: 'ls' },
        { key: 'NX', value: 'nx' },
        { key: 'RX', value: 'rx' },
        { key: 'UX', value: 'ux' },
      ],
      mazda: [
        { key: '1', value: '1' },
        { key: '2', value: '2' },
        { key: '3', value: '3' },
        { key: '5', value: '5' },
        { key: '6', value: '6' },
        { key: 'CX3', value: 'cx3' },
        { key: 'CX5', value: 'cx5' },
        { key: 'CX7', value: 'cx7' },
        { key: 'CX9', value: 'cx9' },
        { key: 'CX30', value: 'cx30' },
        { key: 'CX60', value: 'cx60' },
        { key: 'MX3', value: 'mx3' },
        { key: 'MX5', value: 'mx5' },
        { key: 'MX6', value: 'mx6' },
        { key: 'MX30', value: 'mx30' },
      ],
      mercedes: [
        { key: 'A', value: 'a' },
        { key: 'B', value: 'b' },
        { key: 'C', value: 'c' },
        { key: 'E', value: 'e' },
        { key: 'ML', value: 'ml' },
        { key: 'R', value: 'r' },
        { key: 'S', value: 's' },
        { key: 'Sprinter', value: 'sprinter' },
      ],
      nissan: [
        { key: 'Juke', value: 'juke' },
        { key: 'Leaf', value: 'leaf' },
        { key: 'Navarra', value: 'navarra' },
        { key: 'Note', value: 'note' },
        { key: 'Pathfinder', value: 'pathfinder' },
        { key: 'Qashqai', value: 'qashwai' },
        { key: 'X-Trail', value: 'xtrail' },
      ],
      opel: [
        { key: 'Ampera', value: 'ampera' },
        { key: 'Astra', value: 'astra' },
        { key: 'Combo', value: 'combo' },
        { key: 'Corsa', value: 'corsa' },
        { key: 'CrossLand', value: 'crossLand' },
        { key: 'Frontera', value: 'frontera' },
        { key: 'GrandLand', value: 'grandLand' },
        { key: 'Insignia', value: 'insignia' },
        { key: 'Meriva', value: 'meriva' },
        { key: 'Mokka', value: 'mokka' },
        { key: 'Vectra', value: 'vectra' },
        { key: 'Zafira', value: 'zafira' },
      ],
      peugeot: [
        { key: '2008', value: '2008' },
        { key: '206', value: '206' },
        { key: '207', value: '207' },
        { key: '208', value: '208' },
        { key: '3008', value: '3008' },
        { key: '307', value: '307' },
        { key: '308', value: '308' },
        { key: '406', value: '406' },
        { key: '407', value: '407' },
        { key: '5008', value: '5008' },
        { key: '508', value: '508' },
        { key: 'Boxer', value: 'boxer' },
        { key: 'Partner', value: 'partner' },
      ],
      porsche: [
        { key: '911', value: 'ampera' },
        { key: 'Boxster', value: 'astra' },
        { key: 'Cayanne', value: 'corsa' },
        { key: 'Cayman', value: 'combo' },
        { key: 'Panamera', value: 'crossLand' },
        { key: 'Taycan', value: 'frontera' },
      ],
      renault: [
        { key: 'Arkana', value: 'arkana' },
        { key: 'Clio', value: 'clio' },
        { key: 'Captur', value: 'captur' },
        { key: 'Clio', value: 'clio' },
        { key: 'Espace', value: 'espace' },
        { key: 'Fluence', value: 'fluence' },
        { key: 'Kadjar', value: 'kadjar' },
        { key: 'Kangoo', value: 'kangoo' },
        { key: 'Koleos', value: 'koleos' },
        { key: 'Laguna', value: 'laguna' },
        { key: 'Megane', value: 'megane' },
        { key: 'Scenic', value: 'scenic' },
        { key: 'Talisman', value: 'talisman' },
        { key: 'Talia', value: 'talia' },
        { key: 'Twingo', value: 'twingo' },
        { key: 'Zoe', value: 'zoe' },
      ],
      seat: [
        { key: 'Alhambra', value: 'alhambra' },
        { key: 'Altea', value: 'altea' },
        { key: 'Cordoba', value: 'cordoba' },
        { key: 'Ibiza', value: 'ibiza' },
        { key: 'Leon', value: 'leon' },
        { key: 'Toledo', value: 'toledo' },
      ],
      skoda: [
        { key: 'Citigo', value: 'citigo' },
        { key: 'Enyaq', value: 'enyaq' },
        { key: 'Fabia', value: 'fabia' },
        { key: 'Karoq', value: 'karoq' },
        { key: 'Kodiaq', value: 'kodiaq' },
        { key: 'Octavia', value: 'octavia' },
        { key: 'Rapid', value: 'rapid' },
        { key: 'Roomster', value: 'roomster' },
        { key: 'Scala', value: 'scala' },
        { key: 'Superb', value: 'superb' },
        { key: 'Yeti', value: 'yeti' },
      ],
      suzuki: [
        { key: 'Baleno', value: 'baleno' },
        { key: 'Ignis', value: 'ignis' },
        { key: 'Jimny', value: 'jimny' },
        { key: 'Kizashi', value: 'kizashi' },
        { key: 'S-Cross', value: 'scross' },
        { key: 'Swift', value: 'swift' },
        { key: 'SX4', value: 'sx4' },
        { key: 'SX4 S-Cross', value: 'sx4scross' },
        { key: 'Vitara', value: 'vitara' },
        { key: 'Wagon R+', value: 'wagonr' },
      ],
      toyota: [
        { key: 'Auris', value: 'auris' },
        { key: 'Avensis', value: 'avensis' },
        { key: 'Aygo', value: 'aygo' },
        { key: 'CHR', value: 'chr' },
        { key: 'Camry', value: 'camry' },
        { key: 'Celica', value: 'celica' },
        { key: 'Corolla', value: 'corolla' },
        { key: 'Hilux', value: 'hilux' },
        { key: 'Land Cruiser', value: 'landcruiser' },
        { key: 'Prius', value: 'prius' },
        { key: 'Rav4', value: 'rav4' },
        { key: 'Supra', value: 'supra' },
        { key: 'Verso', value: 'verso' },
        { key: 'Yaris', value: 'yaris' },
      ],
      volkswagen: [
        { key: 'Amarok', value: 'amarok' },
        { key: 'Arteon', value: 'arteon' },
        { key: 'Bora', value: 'bora' },
        { key: 'Caddy', value: 'caddy' },
        { key: 'CC', value: 'cc' },
        { key: 'Crafter', value: 'crafter' },
        { key: 'Golf', value: 'golf' },
        { key: 'ID', value: 'id' },
        { key: 'Jetta', value: 'jetta' },
        { key: 'Lupo', value: 'lupo' },
        { key: 'Multivan', value: 'multivan' },
        { key: 'Passat', value: 'passat' },
        { key: 'Phaeton', value: 'phaeton' },
        { key: 'Polo', value: 'polo' },
        { key: 'Scirocco', value: 'scirocco' },
        { key: 'Sharan', value: 'sharan' },
        { key: 'T-Cross', value: 'tcross' },
        { key: 'T-Roc', value: 'troc' },
        { key: 'Tiguan', value: 'tiguan' },
        { key: 'Touareg', value: 'touareg' },
        { key: 'Touran', value: 'touran' },
        { key: 'Transporter', value: 'transporter' },
        { key: 'Up', value: 'up' },
      ],
      volvo: [
        { key: 'C30', value: 'C30' },
        { key: 'C40', value: 'C40' },
        { key: 'C70', value: 'C70' },
        { key: 'S40', value: 'S40' },
        { key: 'S60', value: 'S60' },
        { key: 'S70', value: 'S70' },
        { key: 'S80', value: 'S80' },
        { key: 'S90', value: 'S90' },
        { key: 'V40', value: 'V40' },
        { key: 'V50', value: 'V50' },
        { key: 'V60', value: 'V60' },
        { key: 'V70', value: 'V70' },
        { key: 'V90', value: 'V90' },
        { key: 'XC40', value: 'xc40' },
        { key: 'XC60', value: 'xc60' },
        { key: 'XC70', value: 'xc70' },
        { key: 'XC90', value: 'xc90' },
      ],
    },
    fuel: [
      { key: 'Dízel', value: 'diesel' },
      { key: 'Benzin', value: 'petrol' },
      { key: 'Hibrid', value: 'hibrid' },
      { key: 'Elektromos', value: 'electric' },
    ],
    transmission: [
      { key: 'Kézi', value: 'manual' },
      { key: 'Félautomata', value: 'semi-automatic' },
      { key: 'Automata', value: 'automatic' },
    ],
    bodyStyle: [
      { key: 'Kompakt', value: 'compact' },
      { key: 'Sedan', value: 'sedan' },
      { key: 'Coupe', value: 'coupe' },
      { key: 'Kombi', value: 'estate' },
      { key: 'SUV', value: 'suv' },
      { key: 'Furgon', value: 'van' },
      { key: 'Egyterű', value: 'minivan' },
      { key: 'Kis', value: 'small' },
      { key: 'Kabrió', value: 'cabriolet' },
      { key: 'Roadster', value: 'roadster' },
    ],
    color: [
      { key: 'Fehér', value: 'white' },
      { key: 'Vörös', value: 'red' },
      { key: 'Kék', value: 'blue' },
      { key: 'Fekete', value: 'black' },
      { key: 'Szürke', value: 'grey' },
      { key: 'Fehér', value: 'white' },
      { key: 'Egyéb', value: 'other' },
    ],
  };
}
